        ;; Global defines for Sound Registers
        NR50 = FF24h           ; Master volume and VIN panning
        NR51 = FF25h           ; sound panning
        NR52 = FF26h           ; global enable register
        NR10 = FF10h           ; Channel 1 sweep
        NR11 = FF11h           ; Channel 1 length timer and duty cycle
        NR12 = FF12h           ; Channel 1 volume and envelope
        NR13 = FF13h           ; Channel 1 period low
        NR14 = FF14h           ; Channel 1 period high & Control
